---
title: "Expected Value Example: Dreidel"
format:
  html:
    math: true
---
Dreidel is a game played during Hanukkah where each player starts by putting 1 piece into the pot and then players rotate around spinning the 4-sided dreidel. If the pot goes to 0 or 1 then all players again put 1 unit into the pot. 

The outcomes are: 

| Dreidel Spin    | Probability | Game Outcome | 
| -------- | ------- | ------- |
| נ (nun)  | $\frac{1}{4}$    | Do nothing | 
| ג (gimel) | $\frac{1}{4}$     | Take whole pot | 
| ש (shin)   | $\frac{1}{4}$   | Take half pot | 
| ה (hei)  | $\frac{1}{4}$    | Put 1 unit into pot | 

Suppose it's your turn to spin and the pot has 6 pieces in it. 

The outcomes are: 

| Dreidel Spin    | Probability | Game Outcome | 
| -------- | ------- | ------- |
| נ (nun)  | $\frac{1}{4}$    | 0 | 
| ג (gimel) | $\frac{1}{4}$     | +6 | 
| ש (shin)   | $\frac{1}{4}$   | +3 | 
| ה (hei)  | $\frac{1}{4}$    | -1 | 

We can now compute the expected value of the spin: 

$$
\begin{equation}
\begin{split}
\mathbb{E}[\text{Dreidel Spin}] &= 0*\frac{1}{4} + 6*\frac{1}{4} + 3*\frac{1}{4} + (-1)*\frac{1}{4} \\
  &= 0 + 1.5 + 0.75 + (-0.25) \\
  &= 2
\end{split}
\end{equation}
$$

(It turns out that the game is "painfully slow" such that a 4 person game where each player starts with 10 units and each spin takes 10 seconds would take an average of 2 hours and 23 minutes (860 spins). [Ben Blatt has suggested improvements](https://www.slate.com/articles/life/holidays/2014/12/rules_of_dreidel_the_hannukah_game_is_way_too_slow_let_s_speed_it_up.html).)